name: sidetopics
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - numpy
  - bottleneck
  - jupyterlab
  - matplotlib
  - seaborn
  - theano
  - pymc3
  - pip
  - pip:
    - spacy
    - aiogram
